### ISSUE TITLE
Question regarding 'max-seq-length'

### ISSUE THREAD

**Issue by mjeensung** [wzhouad/ATLOP#1]
Thank you for this great work.

I've encountered a warning during running prepro.py.

"WARNING:transformers.tokenization_utils:Token indices sequence length is longer than the specified maximum sequence length for this model (559 > 512). Running this sequence through the model will result in indexing errors"

As far as I know, the maximum sequence length of BERT Model input is 512 (Like the warning says), and the default max-seq-length in your code is '1024'.

My question is that, is 'input_ids' in which length is over 512 truncated before running BERT Model? Or is it just okay with input with over 512 length?

**Comment by wzhouad** [comment]
Hi Mujeen,

You can safely ignore this warning. I've enabled the model to process inputs with length 1024 by splitting then combining them (in ``long_seq.py``).

**Comment by mjeensung** [comment]
Thank you for your answer.
