### ISSUE TITLE
How to get the rel2id.json

### ISSUE THREAD

**Issue by sshhhll** [wzhouad/ATLOP#11]
I don't know how to get the rel2id.json in the meta directory. Where is the rel2id.json?
Thanks!

**Comment by wzhouad** [comment]
[here](https://drive.google.com/drive/folders/1Ri3LIILKKBi3aBJjUVCOBpGX5PpONHRK).

**Comment by sshhhll** [comment]
> [here](https://drive.google.com/drive/folders/1Ri3LIILKKBi3aBJjUVCOBpGX5PpONHRK).

**Thank you!!!**
