### ISSUE TITLE
Where did the "/meta/rel2id.json" come from?

### ISSUE THREAD

**Issue by AQA6666** [wzhouad/ATLOP#18]
I only want to use DocRED dataset,and there is only "rel_info.json" in it.
Could you please tell me how can I get rel2id.json?I try to rename rel_info.json to rel2id.json but ValueError: invalid literal for int() with base 10: 'headquarters location' occured in 
  File "train.py", line 197, in main
    train_features = read(train_file, tokenizer, max_seq_length=args.max_seq_length)
  File "/home/kw/ATLOP/prepro.py", line 56, in read_docred
    r = int(docred_rel2id[label['r']])
Thanks for your attention,I'm waiting for your reply.

**Comment by wzhouad** [comment]
Check #11

**Comment by AQA6666** [comment]
> Check #11

Thank you！
