### ISSUE TITLE
Any plans to release the codes for CDR?

### ISSUE THREAD

**Issue by mjeensung** [wzhouad/ATLOP#2]
Hello Zhou

Thank you for releasing the codes of your work.
In your paper, it has the experiment results on CDR.
I want to reproduce the performance using the CDR dataset on your approach.
Do you have any plans to release the codes for CDR?

**Comment by wzhouad** [comment]
The model on CDR is the same as DocRED, but their training and evaluation are massively different. I’m still working on refining my CDR & GDA code. Hopefully I will release the code in early Nov.

**Comment by mjeensung** [comment]
Great! I can't wait to see it 👍

**Comment by wzhouad** [comment]
I've released the code for CDR.

**Comment by mjeensung** [comment]
Thank you!
I could run the code without any problems 👍
