### ISSUE TITLE
The best results of same random seed are different at each time  when I trained the ATLOP

### ISSUE THREAD

**Issue by Lanyu123** [wzhouad/ATLOP#21]
Hello 
I trained the ATLOP with same random seed=66 every time, but the final best result are different. Have you met the same situation before?  thank you for your replying.

**Comment by wzhouad** [comment]
Check #5

**Comment by Lanyu123** [comment]
Thank you sir, one more question，Since the best results are different with same random seed, the results mentioned in your paper are trained with the same random seed (like 66) or trained with different random seed and averaged them?

**Comment by wzhouad** [comment]
They are the average of 5 runs using different random seeds.

**Comment by Lanyu123** [comment]
okay，thank you for your answer, best wishes to you!
