### ISSUE TITLE
How to get test score？

### ISSUE THREAD

**Issue by HenryWang628** [wzhouad/ATLOP#23]
“The program will generate a test file result.json in the official evaluation format. You can compress and submit it to Colab for the official test score.”
After training the ATLOP, I did get the result.json. I submited the file to the Codalab of DocRED after compressing it. But I got nothing in the score, am I using the right way to get the F1 and IgF1 0f test set?

![image](https://user-images.githubusercontent.com/50401924/116087536-87b49080-a6d3-11eb-918b-c4d7b21523bf.png)

![image](https://user-images.githubusercontent.com/50401924/116087038-0c52df00-a6d3-11eb-8ea8-8d46a8c1fad1.png)

**Comment by wzhouad** [comment]
Evaluation can be slow sometimes. Check this page later.
