### ISSUE TITLE
end_tokens for RoBERTa?

### ISSUE THREAD

**Issue by xiaoyuxin1002** [wzhouad/ATLOP#27]
Hi, could you please explain why you used two sep_token_id's for RoBERTa but only one sep_token_id for BERT? Thanks!
https://github.com/wzhouad/ATLOP/blob/1db77ab8bc4fe5f7f8c23067ea17055d58b310a3/model.py#L31

**Comment by wzhouad** [comment]
Looks like a bug in code.
