### ISSUE TITLE
Mention embedding

### ISSUE THREAD

**Issue by mk2x15** [wzhouad/ATLOP#28]
Hi there, thanks for your nice work. I'm a bit confused that in the function get_hrt(), do you use the embedding of the first subword token as the mention embedding instead of summing up all the wordpieces? So the offset used here is due to the insertion of especial token "*" ? Please correct me if I'm wrong, thanks!

**Comment by wzhouad** [comment]
The offset is because of the ``<s>`` token or the ``<CLS>`` token in roberta/bert at the start of text.

**Comment by mk2x15** [comment]
> The offset is because of the `<s>` token or the `<CLS>` token in roberta/bert at the start of text.

Thanks. I also notice that you use the start index from "entity_pos" to select the first subword of mention, but I think they should be used for word-level tokens, is it still correct for workpieces?

**Comment by wzhouad** [comment]
The word positions have been mapped to subtokens.

**Comment by mk2x15** [comment]
Got it! Thanks a lot!
