### ISSUE TITLE
Is there a reason why the lengths of each chunk for the CDR dataset is 17 and not 23?

### ISSUE THREAD

**Issue by seanswyi** [wzhouad/ATLOP#8]
Hi. I'm currently trying to run your model with the BC5CDR dataset. I've noticed that you've set the size of each data chunk to be 17 rather than 23 on line 157 of `prepro.py`. Is there a reason why you did this? I'm under the impression that each sample in the CDR dataset is of length 23, and dividing the total length by 23 gives us an event number (e.g., 138 // 23 == 6). Setting the size to 17 also returns an assertion error in the `chunks` function.

Just curious if I'm missing anything. Thanks!

**Comment by wzhouad** [comment]
Hi,

The pre-processed datasets of edge-oriented-graph have a chunk size of 17.

**Comment by seanswyi** [comment]
Ah my bad. Upon inspection I realized I'm using a different dataset under the same name. I'll close this issue, thanks.
