### ISSUE TITLE
Why do we not recalculate recall for the ignored setting?

### ISSUE THREAD

**Issue by seanswyi** [wzhouad/ATLOP#9]
Hi. I noticed that when we calculate the Ign F1 score, we only recalculate the precision but not the recall. Is there any reason why this is the case? I would think that we should recalculate both, but if I'm misunderstanding something please let me know.

Thanks!

**Comment by wzhouad** [comment]
My evaluation script is the same as the official one. I have no idea why the authors of DocRED skip calculating the Ign recall.

**Comment by seanswyi** [comment]
Thanks for the quick reply. I'll close this and open an Issue on DocRED's GitHub then. :)
